### ISSUE TITLE
爬取下来的数据有重复

### ISSUE THREAD

**Issue by 97thjingba** [maomao1234567/poker_sanic#1]
![image](https://user-images.githubusercontent.com/39749571/48837347-11076080-edc0-11e8-8e4d-cb8d784cdaca.png)

![image](https://user-images.githubusercontent.com/39749571/48837360-1795d800-edc0-11e8-9d54-e9846c9eb843.png)

数据里还有很多应该也有重复.

**Comment by SongbaiLFLY** [comment]
我将dont_filter的去重关了，应删除

**Comment by SongbaiLFLY** [comment]
已更新
